### ISSUE TITLE
when use vite-build,  how to change the port in the production ?  nodejs plateform

### ISSUE THREAD

**Issue by sperains** [honojs/vite-plugins#195]

**Comment by sperains** [comment]
when i write code like below, and then run `vite build`,  and run `node dist/index.js`, trigger error
`import { Hono } from "hono";

const app = new Hono();

app.get("/", (c) => {
  return c.text("Hello Hono!4");
});

export default {
  fetch: app.fetch,
  port: 3333,
};
`

TypeError: Cannot read properties of undefined (reading 'map')
    at It.route (file:///Users/sperains/rainswork/hono_app/dist/index.js:1:12694)
    at file:///Users/sperains/rainswork/hono_app/dist/index.js:1:29432
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v22.11.0

**Comment by sperains** [comment]
@JsonSong89  我放弃用这个打包了, 改用tsup, 轻松加愉快

**Comment by JsonSong89** [comment]
> @JsonSong89 我放弃用这个打包了, 改用tsup, 轻松加愉快

确实,hono是个好框架,但vite还是不太适配
尤其这种在插件里面藏代码,然后影响构建产物,还不提供hook方式的,过于邪典了.

**Comment by q1uxu** [comment]
I want to change the port, but no way to do so..

**Comment by JsonSong89** [comment]
> I want to change the port, but no way to do so..

哈哈 我寻思这框架也不是国产啊,怎么都是国人... 
没地方配置port的,他是在构建环节,又创建了一个mainApp ,然后把你的原来的app当做子路由,关键这个环节一没有处理你原来的app的变量,二没有读取环境变量
除了改代码,无解

**Comment by JsonSong89** [comment]
看了下源码,发现还是留了一个hook: 
不过插件的配置里面写代码,这个说实话还是有点接受不了 
```ts
{
        plugins: [
            build({
                entry: "./src/apps/hello.ts",
                output: "hono_hello.mjs",
                minify: false,
                entryContentAfterHooks: [(appName, options) => {
                    console.log("entryContentAfterHooks 触发")
                    return ` 
                     import {serve} from '@hono/node-server'
                     const run_port = parseInt(process.env.PORT) || 3002
                     serve({
        fetch: ${appName}.fetch,
        port: run_port,
    }, info => {
        console.log(\`Server is running on \${JSON.stringify(info)}\`);
    })
                     `
                }]
            }),
            devServer({
                entry: "./src/apps/hello.ts"
            }),
        ]
    }
```

**Comment by JsonSong89** [comment]
tsup 也有问题 
没法用 import.meta  ,等于一下子脱离hono的构建生态了

**Comment by yusukebe** [comment]
The `port` option is introduced in the new version `@hono/vite-build@1.2.0`. It resolves this problem.

This is fixed by #198

**Comment by sperains** [comment]
> The `port` option is introduced in the new version `@hono/vite-build@1.2.0`. It resolves this problem.
> 
> This is fixed by #198

ok. thank you
